### ISSUE TITLE
Pagination does not work when hidden ("ngIf" directive)

### ISSUE THREAD

**Issue by Miqueliu** [Morgul/ui-bootstrap4#52] opened 2019-08-09 07:02 UTC
[Here](https://jsfiddle.net/rg36mk2j/) is a live code showing to you that the pagination component does not work correctly. The trouble exists when the directive is firstly hidden (by "ngIf" native directive).

For achieve to view this issue, it is necessary watch console logs; clicking visibility checkbox and changing page positions. It is not refreshing scope.

**Comment by ElitenetDenmark** [comment] 2019-09-28 13:09
To solve the issues please use Angular Styleguide and use "controllerAs View Syntax".
https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md#style-y030
And
https://stackoverflow.com/questions/31838265/what-can-be-the-reason-to-use-controlleras-property

Markup:
`  <main class="container">
        <section ng-controller="PaginationController as page">
            <ul uib-pagination total-items="page.totalItems" ng-model="page.currentPage" ng-change="page.pageChanged()"></ul>
            <hr>
            <label><input type="checkbox" ng-model="visible"> Visible</label>
            <ul uib-pagination total-items="page.totalItems" ng-model="page.currentPage" ng-change="page.pageChanged()" ng-if="visible"></ul>
        </section>
    </main>`


Script:
```
  (function () {
  angular
    .module('app', ['ui.bootstrap'])
    .controller('PaginationController', PaginationController);

  function PaginationController($scope) {

    vm = this;
    vm.totalItems = 100;
    vm.currentPage = 1;
    vm.pageChanged = pageChanged;

    vm.visible = false;

    function pageChanged() {
      console.log('currentPage:',  vm.currentPage);
    }
  }
})();
```

**Comment by Morgul** [comment] 2019-10-05 01:33
@ElitenetDenmark Thank you for providing the correct answer. I hadn't caught that; it's been long enough since I was developing in Angular 1.x I forgot about that bug.

I'm closing this, as it's not a bug in the library.

**Closed by Morgul** 2019-10-05 01:33 UTC
Labels: bug, help wanted
